#%RAML 1.0
title: Test - API Version Example
version: 2.0
baseUri: https://localhost:8082/api/v2.0

/hello:
  get:
    queryParameters: 
      name:
        type: string
    responses: 
      200:
        body: 
          application/json:
            example: |
              {"V2 message" : "hello friend - world"}
            